##spring.application.name=DEPARTMENT-SERVICE
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/department_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

#step 2
eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/eureka

#for auto refresh
spring.boot.message=hello , Department detail


#E:\2026\project\sts\project_udemy\springboot-microservice\department-service>
#java -jar -Dserver.port=8082 target/department-service-0.0.1-SNAPSHOT.jar

#
